name: "✨ Feature request"
description: Suggest a feature
labels: ["type/feature", "priority/P2"]
body:
  - type: textarea
    id: story
    attributes:
      {
        label: User story,
        description: "As a <role>, I want <capability> so that <benefit>.",
      }
    validations: { required: true }
  - type: textarea
    id: ac
    attributes: { label: Acceptance criteria, value: "- [ ] ..." }
  - type: dropdown
    id: area
    attributes:
      {
        label: Area,
        options:
          [area/frontend, area/backend, area/core, area/data, area/devops],
      }
